--x�a d? li?u ?? c?t ?? kh�ng b? tr�ng --
DROP TABLE SinhVien_Lop;
DROP TABLE Diem_MonHoc;
DROP TABLE Diem_SinhVien;
DROP TABLE HocPhi;
DROP TABLE hocphirieng;
DROP TABLE Diem;
DROP TABLE MonHoc;
DROP TABLE Lop;
DROP TABLE NhatKyHeThong;
DROP TABLE SinhVien CASCADE CONSTRAINTS; 
COMMIT;
--t?o b?ng sinh vi�n--
CREATE TABLE SinhVien (
    MaSV VARCHAR2(10) PRIMARY KEY,
    HoTen VARCHAR2(100),
    NgaySinh DATE,
    SDT VARCHAR2(15),
    DiaChi VARCHAR2(200),
    Email VARCHAR2(50),
    TenDangNhap VARCHAR2(50),
    MatKhau VARCHAR2(256),
    VaiTro VARCHAR2(20), 
    EncryptedKey VARCHAR2(2000),
    ChuKySo VARCHAR2(2000)    
);
-- t?o b?ng m�n h?c--
CREATE TABLE MonHoc (
    MaMH VARCHAR2(10) PRIMARY KEY,
    TenMH VARCHAR2(100),
    SoTinChi NUMBER
);
-- t?o b?ng l?p --
CREATE TABLE Lop (
    MaLop VARCHAR2(10) PRIMARY KEY,
    TenLop VARCHAR2(50),
    SiSo NUMBER
);
-- tsoj b?ng ?i?m --
CREATE TABLE Diem (
    MaDiem VARCHAR2(10) PRIMARY KEY,
    DiemSo FLOAT(2),
    FK_SV_Diem VARCHAR2(10),
    FK_MH_Diem VARCHAR2(10),
    OLS_LABEL RAW(2000), 
    CONSTRAINT fk_diem_sinhvien FOREIGN KEY (FK_SV_Diem) REFERENCES SinhVien(MaSV),
    CONSTRAINT fk_diem_monhoc FOREIGN KEY (FK_MH_Diem) REFERENCES MonHoc(MaMH)
);
-- t?o b?ng ?i?m sinh vi�n --
CREATE TABLE Diem_SinhVien (
    FK_SV_DiemSV VARCHAR2(10),
    FK_Diem_DiemSV VARCHAR2(10),
    CONSTRAINT pk_diem_sinhvien PRIMARY KEY (FK_SV_DiemSV, FK_Diem_DiemSV),
    CONSTRAINT fk_diem_sinhvien_sv FOREIGN KEY (FK_SV_DiemSV) REFERENCES SinhVien(MaSV),
    CONSTRAINT fk_diem_sinhvien_diem FOREIGN KEY (FK_Diem_DiemSV) REFERENCES Diem(MaDiem)
);
-- t?o b?ng ?i?m m�n h?c --
CREATE TABLE Diem_MonHoc (
    FK_Diem_DMH VARCHAR2(10),
    FK_MH_DMH VARCHAR2(10),
    CONSTRAINT pk_diem_monhoc PRIMARY KEY (FK_Diem_DMH, FK_MH_DMH),
    CONSTRAINT fk_diem_monhoc_diem FOREIGN KEY (FK_Diem_DMH) REFERENCES Diem(MaDiem),
    CONSTRAINT fk_diem_monhoc_monhoc FOREIGN KEY (FK_MH_DMH) REFERENCES MonHoc(MaMH)
);
-- t?i b?ng sinh vi�n l?p--
CREATE TABLE SinhVien_Lop (
    FK_SV_SL VARCHAR2(10),
    FK_Lop_SL VARCHAR2(10),
    CONSTRAINT pk_sinhvien_lop PRIMARY KEY (FK_SV_SL, FK_Lop_SL),
    CONSTRAINT fk_sinhvien_lop_sv FOREIGN KEY (FK_SV_SL) REFERENCES SinhVien(MaSV),
    CONSTRAINT fk_sinhvien_lop_lop FOREIGN KEY (FK_Lop_SL) REFERENCES Lop(MaLop)
);
-- t?o b?ng hoc phi --
CREATE TABLE HocPhi(
    MaHP VARCHAR2(10) PRIMARY KEY,
    MaSV VARCHAR2(10),
    SoTien NUMBER(10, 2),
    NgayThanhToan DATE,
    TrangThai VARCHAR2(20),
    GhiChu VARCHAR2(500),
    SoTKNH_Goc VARCHAR2(50),      
    SoTKNH_MaHoa RAW(2000),     
    CONSTRAINT fk_hocphi_sinhvien FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
);
-- t?o b?nh nh?t k� h? th?ng --
CREATE TABLE NhatKyHeThong (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TaiKhoan VARCHAR2(50),
    HanhDong VARCHAR2(100),
    ThoiGian TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrangThai VARCHAR2(50),
    GhiChu VARCHAR2(255)
);


INSERT INTO Lop (MaLop, TenLop, SiSo) VALUES ('L01', 'ATTT_K14', 50);
INSERT INTO Lop (MaLop, TenLop, SiSo) VALUES ('L02', 'QTM_K14', 45);


INSERT INTO MonHoc (MaMH, TenMH, SoTinChi) VALUES ('MH001', 'Bao Mat Co So Du Lieu', 3);
INSERT INTO MonHoc (MaMH, TenMH, SoTinChi) VALUES ('MH002', 'Quan Tri Mang', 4);
INSERT INTO MonHoc (MaMH, TenMH, SoTinChi) VALUES ('MH003', 'Tri Tue Nhan Tao', 3);

INSERT INTO SinhVien (MaSV, HoTen, NgaySinh, SDT, DiaChi, Email, TenDangNhap, MatKhau, VaiTro, EncryptedKey, ChuKySo)
VALUES ('ADMIN01', 'Quan Tri Vien', DATE '1990-01-01', '0909123456', 'Hanoi', 'admin@school.edu', 'admin', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 'ADMIN',
'RCOsm8GnieSbyssaeuWdcfxknpuScrk88Oey3uBB/YNf/GyISWQ3c6FUgKFk6pk8o8H1zcgxfYhQJtqTPr3wl4sHRV6mZsIWqAtK/KAL1rgX1sqPcdX3Vdg8FJcJQEXDnsDNbjrNOtQFJDooex8wgI8ka6GXnfCZOHRq91nFNTnXXZ8JjXKQbRAeYpZCB5YBIGrxvOilf4A3BrKFFiMttpIOOUmZAWOFgwZqbAI9zUKWZII3wqwCXj77sz6RY18nrqjWNu8ztmG7je4F1STAjDPjytMnHYjaoX1zNPVugPGi4vrc3tJGeEWICY7AC32Ih0t9kJ9zW2xv2yPASo3ysA==',
'kC3Nmgiz48ajkXWU9eudseYPCvK4/jNUyr3DXtiUwyO1wUUSr4C6QyVk0Au96WeaQ4aPMOKJCq6hJ3oIsWTnwxwsH2QDR9kdppBEF0yEvK9mN7Jeu3JoKGWR+V1eaK8BjbzEfocYVM0jDwuNOfXE4cEGcfJ3eYRqeW79UnA7aT/08tblbq8LghN/IZCQwgOFX3WfUhZmY2HxL4l+GglWqVtGCveK3hD3Sp0eJoMmGE7X5Z7K4KjqufNt2QWUvkc2llfV1VSGEj/vXXmA0E1JzcFmsi1MsSgv6lJxWDygNqobIlVrSi7Ffvty3ZpCxgtIRkSdsrDO1rh8biOtEAwgMQ==');

INSERT INTO SinhVien (MaSV, HoTen, NgaySinh, SDT, DiaChi, Email, TenDangNhap, MatKhau, VaiTro)
VALUES ('SV001', 'Nguyen Van An', DATE '2003-05-10', '0901234567', 'TPHCM', 'an.nv@school.edu', 'sv001', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 'SV');

INSERT INTO SinhVien (MaSV, HoTen, NgaySinh, SDT, DiaChi, Email, TenDangNhap, MatKhau, VaiTro)
VALUES ('SV002', 'Tran Thi Binh', DATE '2003-08-20', '0908765432', 'Danang', 'binh.tt@school.edu', 'sv002', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 'SV');

INSERT INTO Diem (MaDiem, DiemSo, FK_SV_Diem, FK_MH_Diem) VALUES ('D001', 9.5, 'SV001', 'MH001');
INSERT INTO Diem (MaDiem, DiemSo, FK_SV_Diem, FK_MH_Diem) VALUES ('D002', 6.0, 'SV001', 'MH002');
INSERT INTO Diem (MaDiem, DiemSo, FK_SV_Diem, FK_MH_Diem) VALUES ('D003', 9.0, 'SV002', 'MH001');
INSERT INTO Diem (MaDiem, DiemSo, FK_SV_Diem, FK_MH_Diem) VALUES ('D004', 7.5, 'SV002', 'MH003');

INSERT INTO SinhVien_Lop (FK_SV_SL, FK_Lop_SL) VALUES ('SV001', 'L01');
INSERT INTO SinhVien_Lop (FK_SV_SL, FK_Lop_SL) VALUES ('SV002', 'L02');

INSERT INTO Diem_MonHoc (FK_Diem_DMH, FK_MH_DMH) VALUES ('D001', 'MH001');
INSERT INTO Diem_MonHoc (FK_Diem_DMH, FK_MH_DMH) VALUES ('D002', 'MH002');
INSERT INTO Diem_MonHoc (FK_Diem_DMH, FK_MH_DMH) VALUES ('D003', 'MH001');
INSERT INTO Diem_MonHoc (FK_Diem_DMH, FK_MH_DMH) VALUES ('D004', 'MH003');

INSERT INTO Diem_SinhVien (FK_SV_DiemSV, FK_Diem_DiemSV) VALUES ('SV001', 'D001');
INSERT INTO Diem_SinhVien (FK_SV_DiemSV, FK_Diem_DiemSV) VALUES ('SV001', 'D002');
INSERT INTO Diem_SinhVien (FK_SV_DiemSV, FK_Diem_DiemSV) VALUES ('SV002', 'D003');
INSERT INTO Diem_SinhVien (FK_SV_DiemSV, FK_Diem_DiemSV) VALUES ('SV002', 'D004');

INSERT INTO HocPhi (MaHP, MaSV, SoTien, NgayThanhToan, TrangThai, GhiChu, SoTKNH_Goc) VALUES ('HP001', 'SV001', 5000000.00, DATE '2025-09-05', N'Da thanh toan', N'Hoc ki 1', '1234567890123456');
INSERT INTO HocPhi (MaHP, MaSV, SoTien, NgayThanhToan, TrangThai, GhiChu, SoTKNH_Goc) VALUES ('HP002', 'SV002', 5000000.00, DATE '2025-09-10', N'Da thanh toan', N'Hoc ki 1', '6543210987654321');
INSERT INTO HocPhi (MaHP, MaSV, SoTien, NgayThanhToan, TrangThai, GhiChu, SoTKNH_Goc) VALUES ('HP003', 'ADMIN01', 5500000.00, NULL, N'Chua thanh toan', N'Hoc ki 1', '1122334455667788');
INSERT INTO HocPhi (MaHP, MaSV, SoTien, NgayThanhToan, TrangThai, GhiChu, SoTKNH_Goc) VALUES ('HP004', 'SV001', 5500000.00, DATE '2025-10-01', N'Da thanh toan', N'Hoc ki 2', '9988776655443322');
COMMIT;

-- Ch��ng 2:
-- 1. M? r?ng c?t SDT: V? m? h�a AES s? t?o ra chu?i k? t? d�i h�n s? �i?n tho?i b?nh th�?ng
ALTER TABLE SinhVien MODIFY SDT VARCHAR2(200);

-- 2. Th�m c?t Avatar: Ki?u BLOB �? ch?a d? li?u h?nh ?nh (M? h�a Lai)
ALTER TABLE SinhVien ADD Avatar BLOB;

-- 3. Th�m c?t EncryptedKey: Ch?a kh�a AES �? ��?c m? h�a b?ng RSA (M? h�a Lai)
ALTER TABLE SinhVien ADD EncryptedKey VARCHAR2(1000);

-- 4. Th�m c?t ChuKySo: Ch?a ch? k? RSA x�c th?c sinh vi�n (M? h�a B?t �?i x?ng)
ALTER TABLE SinhVien ADD ChuKySo VARCHAR2(2000);

COMMIT;

-- Ch?y test d? li?u 
SELECT MaSV, TenDangNhap, MatKhau, SDT, EncryptedKey, ChuKySo 
FROM SinhVien 
ORDER BY MaSV DESC;

SELECT Avatar FROM SinhVien


-- m� h�a t�i kho?n ng�n h�ng --
DECLARE
    encryption_key RAW(32) := DBMS_CRYPTO.RANDOMBYTES(32);
    encryption_type PLS_INTEGER := DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5;
    iv_vector RAW(16) := DBMS_CRYPTO.RANDOMBYTES(16);
BEGIN
    FOR rec IN (SELECT MaHP, SoTKNH_Goc FROM HocPhi WHERE SoTKNH_Goc IS NOT NULL)
    LOOP
        UPDATE HocPhi
        SET SoTKNH_MaHoa = DBMS_CRYPTO.ENCRYPT(
                                utl_i18n.string_to_raw(rec.SoTKNH_Goc, 'AL32UTF8'),
                                encryption_type,
                                encryption_key,
                                iv_vector
                            )
        WHERE MaHP = rec.MaHP;
    END LOOP;
    COMMIT;
END;
SELECT MaSV, SoTKNH_Goc, SoTKNH_MaHoa FROM HocPhi;
-- t?o tablespace ?? ch?a b?ng hoc phi --
CREATE TABLESPACE HOCPHI_DATA
DATAFILE 'C:\USERS\ASUS\DOWNLOADS\ORADATA\ORCL1\DATAFILE\HOCPHI_DATA01.DBF' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE TABLESPACE TBS_QLSV
DATAFILE 'C:\APP09\ORACLE\BASE\ORADATA\ORCLSV\DATAFILE\qlsv_data.dbf'
SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 2048M;

CREATE TABLE hocphirieng(
    MaHP VARCHAR2(10) PRIMARY KEY,
    MaSV VARCHAR2(10),
    SoTien NUMBER(10, 2),
    NgayThanhToan DATE,
    TrangThai VARCHAR2(20),
    GhiChu VARCHAR2(500),
    CONSTRAINT fk_hocphirieng_sinhvien FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
)TABLESPACE HOCPHI_DATA;


CREATE PROFILE PRO_SINHVIEN LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 30
    PASSWORD_LOCK_TIME 1
    SESSIONS_PER_USER 5;
-- t?o user v� role --
CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_SINHVIEN;
CREATE ROLE ROLE_GIANGVIEN;
GRANT CREATE SESSION TO ROLE_SINHVIEN;
GRANT CREATE SESSION, CREATE TABLE TO ROLE_ADMIN;

DROP USER QuanLySinhVien CASCADE;
CREATE USER QuanLySinhVien IDENTIFIED BY 123
DEFAULT TABLESPACE USERS 
PROFILE PRO_SINHVIEN;
GRANT CONNECT, RESOURCE TO QuanLySinhVien;
GRANT UNLIMITED TABLESPACE TO QuanLySinhVien;

DROP USER SV001_DB CASCADE;
CREATE USER SV001_DB IDENTIFIED BY 123
DEFAULT TABLESPACE USERS 
PROFILE PRO_SINHVIEN;
GRANT CREATE SESSION TO SV001_DB;

BEGIN
    SA_SYSDBA.CREATE_POLICY(policy_name => 'ACCESS_DIEM', column_name => 'OLS_LABEL');
END;

EXEC SA_COMPONENTS.CREATE_LEVEL('ACCESS_DIEM', 1000, 'PUB', 'Public');
EXEC SA_COMPONENTS.CREATE_LEVEL('ACCESS_DIEM', 2000, 'CONF', 'Confidential');


GRANT ACCESS_DIEM_DBA TO QuanLySinhVien;


BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
        policy_name => 'ACCESS_DIEM',
        schema_name => 'QuanLySinhVien',
        table_name  => 'Diem',
        table_options => 'READ_CONTROL, WRITE_CONTROL'
    );
END;
EXEC SA_USER_ADMIN.SET_USER_LABELS('ACCESS_DIEM', 'QuanLySinhVien', 'CONF', 'CONF', 'CONF', 'CONF');

AUDIT SESSION;
AUDIT CREATE SESSION WHENEVER SUCCESSFUL;
AUDIT CREATE SESSION WHENEVER NOT SUCCESSFUL;
AUDIT SELECT ON QuanLySinhVien.SinhVien BY ACCESS;
AUDIT SELECT ON QuanLySinhVien.Diem BY ACCESS;

CREATE OR REPLACE CONTEXT CTX_QLSV USING Pkg_Security;

CREATE OR REPLACE PACKAGE Pkg_Security AS
    PROCEDURE Set_User(p_user IN VARCHAR2);
END Pkg_Security;


CREATE OR REPLACE PACKAGE BODY Pkg_Security AS
    PROCEDURE Set_User(p_user IN VARCHAR2) IS
    BEGIN
       
        DBMS_SESSION.SET_IDENTIFIER(p_user);
    END;
END Pkg_Security;



CREATE OR REPLACE FUNCTION Fn_VPD_Diem (
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
) RETURN VARCHAR2 AS
    v_user VARCHAR2(50);
BEGIN
    v_user := SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER');
    IF v_user = 'admin' OR v_user = 'ADMIN01' THEN 
        RETURN NULL;
    ELSE
    
        RETURN 'FK_SV_Diem = ''' || v_user || '''';
    END IF;
END Fn_VPD_Diem;



BEGIN
    
    BEGIN
        DBMS_RLS.DROP_POLICY(USER, 'DIEM', 'VPD_XEM_DIEM');
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;


    DBMS_RLS.ADD_POLICY (
        object_schema => USER,
        object_name   => 'Diem',
        policy_name   => 'VPD_XEM_DIEM',
        function_schema => USER,
        policy_function => 'Fn_VPD_Diem',
        statement_types => 'SELECT'
    );
END;


UPDATE Diem
SET OLS_LABEL = CHAR_TO_LABEL('ACCESS_DIEM', 'CONF')
WHERE DiemSo >= 8.0;

UPDATE Diem
SET OLS_LABEL = CHAR_TO_LABEL('ACCESS_DIEM', 'PUB')
WHERE DiemSo < 8.0;
COMMIT;

-- t?o vpd ch? m?i sinh vien coi diem cua minh --
DBMS_OUTPUT.PUT_LINE('--- KI?M TH? VPD ---');
EXEC Pkg_Security.Set_User('sv001');
SELECT 'SV001 (sv001)' AS NguoiDung, MaDiem, DiemSo, FK_SV_Diem FROM Diem;
EXEC Pkg_Security.Set_User('sv002');
SELECT 'SV002 (sv002)' AS NguoiDung, MaDiem, DiemSo, FK_SV_Diem FROM Diem;
EXEC Pkg_Security.Set_User('admin');
SELECT 'Admin (admin)' AS NguoiDung, MaDiem, DiemSo, FK_SV_Diem FROM Diem;
-- t?o vpd ch? sinh vien coi l?ch s? thanh to�n --
SET SERVEROUTPUT ON;
DBMS_OUTPUT.PUT_LINE('ch? xem ???c l?ch s? ?�ng ti?n');
EXEC Pkg_Security.Set_User('sv001');
SELECT
    'SV001 (sv001)' AS NguoiDung,
    MaHP,
    MaSV,
    SoTien,
    TrangThai,
    GhiChu
FROM HocPhi
ORDER BY MaHP;

EXEC Pkg_Security.Set_User('sv002');
SELECT
    'SV002 (sv002)' AS NguoiDung,
    MaHP,
    MaSV,
    SoTien,
    TrangThai, 
    GhiChu
FROM HocPhi
ORDER BY MaHP;


INSERT INTO HocPhi (MaHP, MaSV, SoTien, NgayThanhToan, TrangThai, GhiChu, SoTKNH_Goc)
VALUES ('HP005', 'SV001', 6000000.00, DATE '2025-12-08', N'Da thanh toan', N'Hoc ki 3 ');
INSERT INTO HocPhi (MaHP, MaSV, SoTien, NgayThanhToan, TrangThai, GhiChu, SoTKNH_Goc)
VALUES ('HP006', 'SV002', 6000000.00, DATE '2025-12-08', N'Da thanh toan', N'Hoc ki 3 ');
COMMIT;
-- gi? l?p x�a v� khoi ph?c d? li?u h?c ph� --
SELECT SYSTIMESTAMP FROM DUAL;
RMAN TARGET 
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
RUN {
  ALLOCATE CHANNEL d1 DEVICE TYPE DISK;
  BACKUP DATABASE PLUS ARCHIVELOG;
  RELEASE CHANNEL d1;
}
INSERT INTO HocPhi (MaHP, MaSV, SoTien, NgayThanhToan, TrangThai, GhiChu, SoTKNH_Goc)
VALUES ('HP007', 'SV003', 7000000.00, SYSDATE, N'Da thanh toan', N'H?c k� 4');
COMMIT;
SELECT MaHP, MaSV, GhiChu FROM HocPhi ORDER BY MaHP;
SELECT file_name FROM dba_data_files WHERE tablespace_name = 'USERS'; 

RMAN TARGET
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
RUN {
  ALLOCATE CHANNEL d1 DEVICE TYPE DISK;
  RESTORE DATABASE
  RESTORE DATABASE UNTIL TIME ;
  RECOVER DATABASE
  RECOVER DATABASE UNTIL TIME ;
  RELEASE CHANNEL d1;
}
ALTER DATABASE OPEN RESETLOGS;
SELECT MaHP, MaSV, SoTien, NgayThanhToan, GhiChu FROM HocPhi ORDER BY MaHP;
